apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: znp7eviku-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-d708a11081.cjfw.p3.openshiftapps.com/rhtap/rhtap-qe:18e034ab9aea3788253a569ef15b468cfc74e5d3@sha256:020d617d67fb3114b7415316faa89c6977ba69a74cc52820d8f34904e30703b1
          name: container-image
